import { useMemo, useState } from "react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Separator } from "@/components/ui/separator";
import {
  FileText, ListChecks, ArrowUpRight, BookOpen, Copy, Check, Download, Clock, Stethoscope,
} from "lucide-react";
import {
  ESCALATION_LADDER, SLA_CIRCULARS, PLAYBOOK_CATEGORY_COLORS,
  type PlaybookEntry,
} from "@/data/cashlessPlaybook";
import { toast } from "@/hooks/use-toast";

/**
 * Standalone escalation checklist generator.
 * Lets the user tick off documents & actions, then export / copy a ready-to-use
 * checklist drafted for the selected cashless denial reason.
 */
export default function ChecklistDialog({
  entry, open, onOpenChange,
}: { entry: PlaybookEntry | null; open: boolean; onOpenChange: (v: boolean) => void }) {
  const [checkedDocs, setCheckedDocs] = useState<Set<string>>(new Set());
  const [checkedActions, setCheckedActions] = useState<Set<number>>(new Set());
  const [copied, setCopied] = useState(false);

  const relevantCirculars = useMemo(() => {
    if (!entry) return [];
    return SLA_CIRCULARS.filter(c => {
      const ctx = `${entry.reason} ${entry.category} ${entry.dept}`.toLowerCase();
      const apt = c.appliesTo.toLowerCase();
      if (apt.includes("psychiatric") && ctx.includes("psychiatr")) return true;
      if (apt.includes("daycare") && (ctx.includes("daycare") || ctx.includes("chemo") || ctx.includes("dialysis"))) return true;
      if (apt.includes("ped") && (ctx.includes("ped") || ctx.includes("pre-existing"))) return true;
      if (apt.includes("implants") && (ctx.includes("implant") || ctx.includes("stent"))) return true;
      if (apt.includes("all health")) return true;
      return false;
    });
  }, [entry]);

  const highlightLevels = useMemo(
    () => entry ? inferEscalationLevels(entry.escalation) : [],
    [entry],
  );

  if (!entry) return null;
  const categoryColor = PLAYBOOK_CATEGORY_COLORS[entry.category] || "hsl(var(--muted))";

  function toggleDoc(d: string) {
    const next = new Set(checkedDocs);
    next.has(d) ? next.delete(d) : next.add(d);
    setCheckedDocs(next);
  }
  function toggleAction(i: number) {
    const next = new Set(checkedActions);
    next.has(i) ? next.delete(i) : next.add(i);
    setCheckedActions(next);
  }

  function buildChecklistText(): string {
    const refs = relevantCirculars.map(c => `${c.name} (${c.reference})`);
    return [
      `CASHLESS DENIAL — ESCALATION CHECKLIST`,
      `=========================================`,
      ``,
      `Department: ${entry!.dept}`,
      `Reason: ${entry!.reason}`,
      `Policy clause: ${entry!.clause}`,
      `Type: ${entry!.type}  ·  Category: ${entry!.category}  ·  TAT: ${entry!.tat}`,
      ``,
      `--- DOCUMENTS REQUIRED ---`,
      ...entry!.docs.map(d => `[${checkedDocs.has(d) ? "x" : " "}] ${d}`),
      ``,
      `--- HOSPITAL ACTION STEPS ---`,
      ...entry!.actions.map((a, i) => `[${checkedActions.has(i) ? "x" : " "}] ${i + 1}. ${a}`),
      ``,
      `--- ESCALATION PATH (${entry!.escalation}) ---`,
      ...ESCALATION_LADDER
        .filter(l => highlightLevels.includes(l.level))
        .map(l => `L${l.level} · ${l.name} — ${l.authority} (TAT ${l.tat})\n      Contact: ${l.contact}`),
      ``,
      refs.length > 0 ? `--- SLA / REGULATORY REFERENCES TO CITE ---` : "",
      ...refs.map(r => `• ${r}`),
      ``,
      `Expected outcome: ${entry!.outcome}`,
      ``,
      `Generated by Insurance Desk`,
    ].filter(Boolean).join("\n");
  }

  function copyChecklist() {
    navigator.clipboard.writeText(buildChecklistText()).then(() => {
      setCopied(true);
      toast({ title: "Checklist copied", description: "Paste into email, doc, or TPA portal." });
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function downloadChecklist() {
    const blob = new Blob([buildChecklistText()], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `checklist-${entry!.sr}-${entry!.reason.slice(0, 40).replace(/[^a-z0-9]+/gi, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "Checklist downloaded" });
  }

  const docProgress = checkedDocs.size / Math.max(entry.docs.length, 1);
  const actionProgress = checkedActions.size / Math.max(entry.actions.length, 1);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-hidden flex flex-col p-0">
        <DialogHeader className="p-5 pb-3 border-b">
          <div className="flex items-center gap-1.5 mb-1">
            <div className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: categoryColor }} />
            <span className="text-[10px] uppercase tracking-wide text-muted-foreground">{entry.category}</span>
          </div>
          <DialogTitle className="text-base">Escalation checklist</DialogTitle>
          <DialogDescription className="text-sm">{entry.reason}</DialogDescription>
          <div className="flex flex-wrap items-center gap-1.5 pt-1">
            <Badge variant="outline" className="text-[10px] gap-1">
              <Stethoscope className="h-3 w-3" /> {entry.dept}
            </Badge>
            <Badge variant="outline" className="text-[10px]">{entry.type}</Badge>
            <Badge variant="outline" className="text-[10px] gap-1">
              <Clock className="h-3 w-3" /> TAT {entry.tat}
            </Badge>
          </div>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5">
          {/* Documents */}
          <section>
            <SectionTitle icon={FileText} count={`${checkedDocs.size}/${entry.docs.length}`}>
              Documents to gather
            </SectionTitle>
            <ProgressBar value={docProgress} />
            <ul className="mt-2 space-y-1.5">
              {entry.docs.map(doc => (
                <li key={doc} className="flex items-start gap-2 text-sm">
                  <Checkbox
                    id={`doc-${doc}`}
                    checked={checkedDocs.has(doc)}
                    onCheckedChange={() => toggleDoc(doc)}
                    className="mt-0.5"
                  />
                  <label htmlFor={`doc-${doc}`} className={`leading-relaxed cursor-pointer ${
                    checkedDocs.has(doc) ? "line-through text-muted-foreground" : "text-foreground/85"
                  }`}>
                    {doc}
                  </label>
                </li>
              ))}
            </ul>
          </section>

          <Separator />

          {/* Actions */}
          <section>
            <SectionTitle icon={ListChecks} count={`${checkedActions.size}/${entry.actions.length}`}>
              Hospital action steps
            </SectionTitle>
            <ProgressBar value={actionProgress} />
            <ol className="mt-2 space-y-1.5">
              {entry.actions.map((step, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  <Checkbox
                    id={`act-${i}`}
                    checked={checkedActions.has(i)}
                    onCheckedChange={() => toggleAction(i)}
                    className="mt-0.5"
                  />
                  <label htmlFor={`act-${i}`} className={`leading-relaxed cursor-pointer ${
                    checkedActions.has(i) ? "line-through text-muted-foreground" : "text-foreground/85"
                  }`}>
                    <span className="font-semibold mr-1">{i + 1}.</span>{step}
                  </label>
                </li>
              ))}
            </ol>
          </section>

          <Separator />

          {/* Escalation path */}
          <section>
            <SectionTitle icon={ArrowUpRight}>Escalation path</SectionTitle>
            <p className="text-xs text-muted-foreground mt-1">{entry.escalation}</p>
            <div className="mt-2 space-y-1.5">
              {ESCALATION_LADDER.map(level => {
                const isHighlight = highlightLevels.includes(level.level);
                return (
                  <div
                    key={level.level}
                    className={`flex items-start gap-3 p-2.5 rounded-md border transition-colors ${
                      isHighlight ? "bg-primary/5 border-primary/30" : "bg-card border-border opacity-60"
                    }`}
                  >
                    <div className={`shrink-0 h-6 w-6 rounded-full text-[11px] font-semibold flex items-center justify-center ${
                      isHighlight ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
                    }`}>
                      L{level.level}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center justify-between gap-2 flex-wrap">
                        <span className="text-xs font-semibold">{level.name}</span>
                        <span className="text-[10px] text-muted-foreground tabular-nums">{level.tat}</span>
                      </div>
                      <p className="text-[11px] text-muted-foreground mt-0.5 leading-relaxed">{level.authority}</p>
                      <p className="text-[10px] text-muted-foreground/80 mt-0.5">{level.contact}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          {relevantCirculars.length > 0 && (
            <>
              <Separator />
              <section>
                <SectionTitle icon={BookOpen}>SLA references to cite</SectionTitle>
                <ul className="mt-2 space-y-1.5">
                  {relevantCirculars.map(c => (
                    <li key={c.reference} className="border rounded-md p-2.5 text-xs">
                      <div className="flex items-center justify-between gap-2 flex-wrap">
                        <span className="font-medium">{c.name}</span>
                        <Badge variant="outline" className="text-[9px] py-0">{c.year}</Badge>
                      </div>
                      <p className="text-[10px] font-mono text-muted-foreground mt-0.5">{c.reference}</p>
                      <p className="text-[11px] text-foreground/80 mt-1">{c.mandate}</p>
                    </li>
                  ))}
                </ul>
              </section>
            </>
          )}
        </div>

        <DialogFooter className="p-4 border-t bg-card sm:justify-between gap-2">
          <p className="text-[11px] text-muted-foreground self-center">
            Expected outcome: <span className="text-foreground/85">{entry.outcome}</span>
          </p>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={downloadChecklist} className="gap-1.5">
              <Download className="h-3.5 w-3.5" /> Download .txt
            </Button>
            <Button size="sm" onClick={copyChecklist} className="gap-1.5">
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied" : "Copy checklist"}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function SectionTitle({
  icon: Icon, children, count,
}: { icon: typeof FileText; children: React.ReactNode; count?: string }) {
  return (
    <div className="flex items-center justify-between gap-2">
      <div className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
        <Icon className="h-3.5 w-3.5" />
        {children}
      </div>
      {count && <span className="text-[10px] tabular-nums text-muted-foreground">{count}</span>}
    </div>
  );
}

function ProgressBar({ value }: { value: number }) {
  return (
    <div className="mt-1.5 h-1 rounded-full bg-muted overflow-hidden">
      <div
        className="h-full bg-primary transition-all"
        style={{ width: `${Math.round(value * 100)}%` }}
      />
    </div>
  );
}

function inferEscalationLevels(escalationText: string): number[] {
  const t = escalationText.toLowerCase();
  const levels: number[] = [1];
  if (t.includes("medical") || t.includes("reviewer") || t.includes("doctor")) levels.push(2);
  if (t.includes("insurer") || t.includes("claims head") || t.includes("cmo") || t.includes("cmd")) levels.push(3);
  if (t.includes("grievance")) levels.push(4);
  if (t.includes("irdai") || t.includes("bima bharosa")) levels.push(5);
  if (t.includes("ombudsman")) levels.push(6);
  if (t.includes("consumer")) levels.push(7);
  if (t.includes("court")) levels.push(8);
  return levels;
}
